---
image: git-registry.m1nd.io/m1nd/molecule-dind:latest

.before_script_template: &check_docker_login
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

stages:
  - test
  - deploy

Sonarqube Scanner:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
    DEBUG: "True"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true
  only:
    - main

Deploy DEV:
  stage: deploy
  environment: dev
  image: node:16.16.0
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

Deploy PROD:
  stage: deploy
  environment: prod
  image: node:16.16.0
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes -environment=production --token=$VERCEL_TOKEN
    - vercel build -prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt -prod --token=$VERCEL_TOKEN
  when: manual
